# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12ad34fdcc82b498c76b5f4551ace9a60756f1ff60b2e705ee0d5f9ca2d2678b0df03e94e73f0da84cf1d81712071c7144f9ab23eefdc4d13854c1c18755d1c4
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

test:
  secret_key_base: 566c0dcfd2147f5eef7eade3b50f8defb39b1241a7e3f02789f5d2300a7668d583ca20af5f94f79222f0573d9aedd998e3f5d2807ef08e3482893bb03f652cf5
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
